[all]
master ansible_host=192.168.1.10 ansible_user=ubuntu
worker1 ansible_host=192.168.1.11 ansible_user=ubuntu
worker2 ansible_host=192.168.1.12 ansible_user=ubuntu

[k8s_master]
master

[k8s_workers]
worker1
worker2

[nginx_group]
master

[k8s_cluster:children]
k8s_master
k8s_workers
